### ISSUE TITLE
English-only donate page

### ISSUE THREAD

**Issue by julia-smith** [INN/umbrella-cpipr#3]
Create a new English donate page for http://periodismoinvestigativo.com/. This page should be in addition to the existing Spanish donate page, so none of the donar buttons throughout the site need to be replaced.

Content should read:

> DONATE TODAY! 
> Support independent non-profit media in Puerto Rico!
> 
> Centro de Periodismo Investigativo (Center for Investigative Journalism) is an independent, 501(c)(3) tax-exempt non-profit media organization that does not accept any kind of government support. Our organization receives donations and support from foundations, institutions and citizens who share our vision of civic empowerment and value the quality of good and ethical journalism. Donations received are tax-deductible in Puerto Rico and the United States. 
> 
> [buttons]
>
>Note: If you prefer to send a check, make it payable to Centro de Periodismo Investigativo and send it to this address: PO Box 6834, San Juan, PR 00914-6834. 

The buttons should go to:

- Network for Good: https://www.networkforgood.org/donation/ExpressDonation.aspx?ORGID2=660705065&vlrStratCode=O2I27FAG%2bW3ZWbuMz3JPs4dHbY2pKZTMVl%2bvfdmxOs9P%2fiEZmN8WcWbNanhaikgc
- PayPal: [They need a new PayPal button]

**Comment by kaylima** [comment]
@julia67 http://periodismoinvestigativo.com/donate/ - For review (visible to logged-in users only).

**Comment by julia-smith** [comment]
Looks good! I went ahead and published it
