### ISSUE TITLE
Full width images/blocks

### ISSUE THREAD

**Issue by lajoiemedia** [INN/umbrella-cpipr#43]
More recent versions of Largo allow for full screen width images/blocks (using the .alignfull class). Can we bring the same capabilities to the CPIPR theme?

(Either by updating to a newer Largo parent theme or by backporting the feature to the cpipr child theme?)

Is this achievable?

**Comment by rocaiguina** [comment]
Hi @lajoiemedia,
Updating the Largo parent is not currently in the backlog, if you want to backport the feature go ahead.
Series like this https://periodismoinvestigativo.com/series/los-chavos-de-maria/ 
which use a full-width template, does that work?

**Comment by lajoiemedia** [comment]
Not sure. It will primarily be a text article, so I don't want the primary text column to be too wide.

**Comment by rocaiguina** [comment]
check the single page template for series

**Comment by lajoiemedia** [comment]
Yes, I've found the series page, but can't seem to make the featured image full width. See screenshot.
<img width="1661" alt="Screenshot 2020-07-30 at 9 52 53 AM" src="https://user-images.githubusercontent.com/57726977/88931376-bee03900-d24a-11ea-811b-746ac8fa5d69.png">
